import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import sassDts from "vite-plugin-sass-dts";

// https://vite.dev/config/
export default defineConfig({
  plugins: [
    react(),
    sassDts({
      // By default only the `development` mode is enabled, which means that the `d.ts` files are generated only:
      //  - when the `dev` command is running
      //  - and after the source files are changed
      // Let's add the `production` mode so that the `d.ts` files are generated by the `build` command as well.
      enabledMode: ["development", "production"],
      esmExport: true,
    }),
  ],
  css: {
    preprocessorOptions: {
      scss: {
        api: "modern-compiler",
      },
    },
  },
  server: { port: 3000 },
});
